Repository sandesh3216/github_learning, pull requests merged in 2024-06, with the labels that each got.

#2 added css
  style .css
Labels: documentation

#3 js file added
  index.js
Labels: question

#5 committed message to index
  index.js
Labels: good first issue
